create table cubes (
    id bigint generated by default as identity,
    name varchar(255),
    serial_number varchar(255),
    primary key (id)
);

create table activity_configs (
    id bigint generated by default as identity,
    side_number integer,
    cube_id bigint,
    primary key (id)
);

create table work_sessions (
    id uuid not null,
    duration_seconds bigint,
    end_time timestamp(6),
    side_number integer,
    start_time timestamp(6) not null,
    cube_id bigint,
    primary key (id)
);

alter table activity_configs
    add constraint fk_activity_configs_cube
    foreign key (cube_id) references cubes;

alter table work_sessions
    add constraint fk_work_sessions_cube
    foreign key (cube_id) references cubes;
